### ISSUE TITLE
Speech streaming sample should have separate request and response handlers

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/php-docs-samples#521] opened 2017-12-22 18:39 UTC
Currently the speech streaming sample just reads a file, sends it, and waits for a response (all serially). But the streaming api is mainly useful for bidi streaming - ie one thread sends the audio in chunks, and one thread listens for dynamic responses. stackoverflow seems to think that [php can handle threads](https://stackoverflow.com/questions/70855/how-can-one-use-multi-threading-in-php-applications), so it'd be nice to get the sample to demonstrate this capability.

Ideally it'd also get the audio from a live source (like a microphone) ^_^ But I'd settle for chunking up an audio file and sending the audio piece by piece (in its own thread). I think the most likely use case is for the php script to receive live audio sent by a browser over a websocket, sending transcripts over the same websocket as it gets them.

**Comment by jerjou** [comment] 2017-12-22 18:41
[These](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/375) [two](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/354) bugs look related as well.

**Comment by meredithslota** [comment] 2023-04-30 21:02
There's a generated sample that addresses this here: https://github.com/googleapis/google-cloud-php/blob/main/Speech/samples/V1/SpeechClient/streaming_recognize.php (for v1) and here: https://github.com/googleapis/google-cloud-php/blob/main/Speech/samples/V2/SpeechClient/streaming_recognize.php (for v2) re: bidirectional streaming speech recognition. However, it's relatively simple and may not address all the questions you raised. Since this issue is quite old (apologies), I'm going to close it out — if the issue is persisting (e.g. folks are still stuck on this), can you please open a new issue describing where you're stuck? Thanks!

**Closed by meredithslota** 2023-04-30 21:02 UTC
Labels: Data Analytics / ML / IoT, type: feature request, samples
