### ISSUE TITLE
google\appengine\runtime\Error not found

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#531] opened 2018-01-05 11:37 UTC
Perhaps some other weird include path issue? It is on the local disk in the expected location:

```
elharo-macbookair99:elharo.com elharo$  vendor/bin/wp --path=wordpress plugin list
PHP Fatal error:  Class 'google\appengine\runtime\Error' not found in /Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/ApplicationError.php on line 22
Fatal error: Class 'google\appengine\runtime\Error' not found in /Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/ApplicationError.php on line 22
elharo-macbookair99:elharo.com elharo$ ls /Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/*Error*
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/ApplicationError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/ArgumentError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/CallNotFoundError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/CancelledError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/CapabilityDisabledError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/DeadlineExceededError.php
/Users/elharo/elharo.com/vendor/google/appengine-php-sdk/google/appengine/runtime/Error.php
...
```

Possibly relevant: initially my entire vendor/google directory was missing from this install (I'm no sure why) and I had to copy it from a different wordpress install.

**Comment by tmatsuo** [comment] 2018-01-05 22:50
Do you set `WP_CLI_PHP_ARGS` env var?

**Comment by elharo** [comment] 2018-01-06 16:31
Yes, WP_CLI_PHP_ARGS was set.

**Comment by bshaffer** [comment] 2019-10-07 19:33
I'm uncertain what the issue is here, but I'm closing it because the PHP 7.2 runtime is now encouraged over the PHP 5.6 runtime, which runs an EOL version of PHP.

**Closed by bshaffer** 2019-10-07 19:33 UTC
Labels: :rotating_light:, triage me
