### ISSUE TITLE
Bootstrap Not Working on Google Cloud WordPress Custom Theme

### ISSUE THREAD

**Issue by bld2104** [GoogleCloudPlatform/php-docs-samples#489] opened 2017-11-21 22:17 UTC
Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
**Mac OS X High Sierra**

Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
**Chrome**

Reduced test cases and potential fixes using CodePen or JS Bin
**I am not totally sure how to create the reduced test case since the issue is that it seems to be completely skipping bootstrap. In my original site, I had the minified bootstrap css as the first lines in my style.css file, and then my custom CSS after that. I thought that was the problem, so I removed that and used the CDN link to boostrap css. That didn't work either so then I tried putting the non-minified bootstrap code directly into my style.css file and again it wouldn't register it. The rest of the CSS (my custom CSS) worked but the bootstrap classes would not. I go into more detail about this below.**

In my first attempt to do this, I created this website as a test on Google Cloud: boxplotdata.com. As you can see, some of the CSS is loading but the bootstrap is not (it's not hiding the smaller versions of things until the screen size changes). This same exact code works perfectly on my non-Google cloud website, boxplotanalytics.com. But when I copied the exact same thing over to the Google Cloud version it stopped working.

I contacted the Bitnami help team since I am using their Wordpress instance on Google Cloud, and in order to try to produce an error for them, I created an entirely new project in Google Cloud, and this time followed tutorials from the Bitnami website in order to make sure I did all steps correctly. This second Google Cloud project is at datakeepteam.com.

I used SFTP to get into the server, and uploaded my theme as I usually do with my non-Google hosts. I got this error when I clicked on Appearance >> Themes in WordPress:

The following themes are installed but incomplete.

Name	Description
boxplot-theme	Stylesheet is not readable.

This happened with the first project too (boxplotdata.com). To fix it, I deleted the bootstrap part of my stylesheet (I had the minified bootstrap as the first part of my stylesheet, then my custom CSS code below that) and then it recognized the stylesheet.

However, this time, I stopped at this point in case this helps solve the problem. Any idea why the bootstrap code isn't being recognized?

Thank you,
Barb

**Comment by jgacuca567** [comment] 2017-11-21 22:22
Post your **app.yaml** file using gist.github.com and when you run errors using `gcloud  app deploy`, what errors are you getting?

**Comment by bld2104** [comment] 2017-11-21 22:49
Hi @jgacuca567 , 

I am completely new to Google Cloud, so I'm sorry if these are beginner questions!

1) I can't find the app.yaml file. I did a bunch of Googling and found [this Google app.yaml reference](https://cloud.google.com/appengine/docs/standard/php/config/appref) which talks about it being in the home directory, but I can't find it anywhere in FileZilla. Do I need to create one? 

2) I installed the Google Cloud SDK, and ran 'gcloud app deploy' - the output is [here](https://gist.github.com/bld2104/8307ae88101e4cbbb59efe4228d42055). I never ran this command before so I am guessing this is not what you were looking for - how do I turn on errors?

Sorry for my noob questions!
Barb

**Comment by jgacuca567** [comment] 2017-11-21 23:28
No worries, 

Was the app.yaml file created?
To test the wordpress app in the `wp-config` change the `WP_DEBUG` to true so that the errors can show. 
The files are not showing https://test2-boxplot-wordpress.appspot.com

**Comment by bld2104** [comment] 2017-11-21 23:54
Okay I changed WP_DEBUG to true.

Yes, I see an app.yaml file now! It has only this in it:

env: flex
runtime: php
runtime_config:
  document_root: .

I should have mentioned, I did point a domain name to this second test, datakeepteam.com. Is that why https://test2-boxplot-wordpress.appspot.com/ is not working? Or is that unrelated?

**Comment by jgacuca567** [comment] 2017-11-22 01:01
For pointing to the right domain we can fix that later. 


Add the following to `app.yaml`

beta_settings: 
    cloud_sql_instances: "Insert Your Cloud SQL Instance Here"

runtime_config:
    document_root: wordpress

env_variables:
    WHITELIST_FUNCTIONS: escapeshellarg, escapeshellcmd, exec, pclose, popen, shell_exec, phpversion, phpuname

If the following doesn't work, Lets do a screen share, and debug together. 
Install Teamviewer https://www.teamviewer.us Then Download the free version.

**Comment by bld2104** [comment] 2017-11-22 01:12
Teamviewer is fine with me, I have it installed. Should I send you the credentials here?

I am not sure where to find my SQL instance (do I need to make one with these instructions?)

**Comment by jgacuca567** [comment] 2017-11-22 01:25
Send me at jgacuca@gmail.com

**Comment by bld2104** [comment] 2017-11-22 02:23
Thanks again for trying over TeamViewer. As promised I am posting the rest here. I created the SQL instance and added it to the app.yaml file. I have two questions from here:

1) Which folder do I upload the app.yaml file to? My theme folder or some other folder?
2) Do I then need to follow these instructions to configure the app.yaml file so that it will read the bootstrap css? https://cloud.google.com/appengine/docs/standard/php/getting-started/serving-static-files

Thank you!
Barb

**Comment by jgacuca567** [comment] 2017-11-22 13:55
<img width="310" alt="screen shot 2017-11-22 at 8 53 28 am" src="https://user-images.githubusercontent.com/4000076/33130867-b940a9b4-cf62-11e7-8e86-40a5c6171cbd.png">

When you installed did you see the vendor file as well, See My screenshot. 

For the bootstrap files should work automatically. Try that let me know.

**Comment by bld2104** [comment] 2017-11-22 14:47
I think I did something wrong, I don't see any of those files. I ran that command in my local terminal using Google SDK. Was I supposed to SSH into my google cloud server and run that command? 

The app.yaml showed up in my local folder on my computer, not on the server. So I guess I need to drag it onto the server via FileZilla? And if so, where do I drag it to?

**Comment by jgacuca567** [comment] 2017-11-22 15:12
Try following the example from https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible, and you should be able to see the following folders, vendor, wordpress, the dosbrandingkedev is my folders name so yours should be boxplot or anything.

**Comment by bld2104** [comment] 2017-11-22 15:16
Before I start the tutorial I just want to double check - are you sure I need to do this if I used the Bitnami installation of WordPress? I'm guessing my site already has to have a database if it's functioning right? (datakeepteam.com is the URL that is pointing to the site currently). I thought Bitnami would have included all this in their packaged installation? 

If not that's fine I can go through with the tutorial but just want to make sure it's right path. 

It's weird that it recognizes my custom CSS (even when the boostrap css is right next to it in the same file) but won't recognize the bootstrap css. Maybe I've identified the problem incorrectly but from my original version (boxplotdata.com is the URL pointing to the first try) it seems that the bootstrap classes are the ones not working. And like I mentioned in the original post, I tried several different ways to get it to recognize those classes - linking to bootstrap externally, putting it in my main style.css file, creating a new bootstrap file in my folder and linking to that, etc.

**Comment by jgacuca567** [comment] 2017-11-22 15:34
You can test, with the tutorial and see if the CSS shows up. 

I haven't used Bitnami yet so thats why I am unsure. 

The database you created already, you can always export the DB. 

for your custom css, is it in a folder or is just style.css?

**Comment by bld2104** [comment] 2017-11-22 16:00
Ok i will give it a try and post back when I am done. It might take me several hours since I have a few other things I have to do today.

It's just style.css in my root folder, I don't have any stylesheets in a separate folder.

**Comment by bld2104** [comment] 2017-11-22 17:41
I am not sure how to do step 7 of the tutorial:

Install a MySql client and verify that the location of the mysql executable file is in your PATH environment variable.

Also the "Setting up the WordPress project" section doesn't seem relevant since I have a working version of WordPress.

**Comment by jgacuca567** [comment] 2017-11-22 18:37
Bear with my long tutorial , it will be much easier long term. We are doing a fresh install to find out the problem. 

Ensure the Cloud SQL API is enabled https://cloud.google.com/sql/docs/mysql/connect-external-app


Open Sequel Pro App
In the Standard Tab Enter 127.0.0.1 as Host then Your username and password from the sql instance and try to connect. 

Open the Command Line 
Go to your directory then run `php -S localhost:8080 -t [Insert name of directory]` This is for PHP

Once you do that, open a browser and run localhost:8080, the Wordpress Install should show. 
Should it succeed run your theme and see if the bootstrap will show.

**Comment by bld2104** [comment] 2017-11-22 18:43
I didn't realize we were doing a fresh install, I'm fine with that, but I feel like now that I know it's a brand new installation, I should be creating a new project for this to keep it separate from the Bitnami one. 

Just to be clear: you want me to start over with an entirely new project in Google Cloud and follow these exact directions (and these directions ONLY) to create a WordPress Instance, is that right? 
https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible

Also, is Sequel Pro this? https://www.sequelpro.com/

**Comment by jgacuca567** [comment] 2017-11-22 19:32
Yes. Yes.

**Comment by bld2104** [comment] 2017-11-22 20:29
Okay great I am making good progress. I got up to this point:

mysql -h 127.0.0.1 -u root --password=[YOUR_SQL_ROOT_PASSWORD]

When I ran that in a new terminal window like they said, I got this error:
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

**Comment by jgacuca567** [comment] 2017-11-22 20:50
Did you succeed in setting up Cloud SQL?

What step are you at currently?

**Comment by bld2104** [comment] 2017-11-22 20:58
On this website:
https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible

I am under the section called "Creating and configuring a Cloud SQL Second Generation instance", number 4. 

Everything else before that I got to run/download/setup successfully.

**Comment by jgacuca567** [comment] 2017-11-22 21:03
Use Sequel Pro, with 127.0.0.1 and your username and password instead .

**Comment by bld2104** [comment] 2017-11-22 22:11
Oh I see that's what Seqeul Pro is for, sorry about that.

Okay I opened Sequel Pro and put in 127.0.0.1 as the host, and what I thought was my username and password but it didn't work. I tried a few other usernames and passwords and they didn't work either. Where would I find my username?

**Comment by jgacuca567** [comment] 2017-11-22 22:19
Did you create a db in sql instance already if not.

DO you see Overview, Users, Databases, Authorization, SSL, Backups, Replicas Operations Tabs?

Click on Users, Create a new user,

**Comment by bld2104** [comment] 2017-11-22 22:56
Ok good, that's what I did. I just tried it again and it's still not working. This is the error it's giving me:

Unable to connect to host 127.0.0.1, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Lost connection to MySQL server at 'reading initial communication packet', system error: 0

**Comment by jgacuca567** [comment] 2017-11-22 22:59
Would you like to screenshare?

**Comment by bld2104** [comment] 2017-11-23 03:23
Thanks for offering, but I'd rather not screen share again. I understand that it's probably easier than this, but at least I will be able to follow this when I do a real run (which I'll need to do when this is over). I will keep trying for the host connection.

**Comment by bld2104** [comment] 2017-11-23 04:05
Okay good news I followed the instructions under the "Configure access to your Cloud SQL instance" section of this page:
https://cloud.google.com/sql/docs/mysql/connect-admin-ip#configure-instance-mysql

and it worked. I am continuing with the rest of the original tutorial now. Will let you know if I run into any further issues.

**Comment by bld2104** [comment] 2017-11-24 18:38
Just want to give you an update - good news and bad. I got much further in the tutorial. I am on the deploy step but got this error:

Updating service [default] (this may take several minutes)...failed.                                                                        
ERROR: (gcloud.app.deploy) Error Response: [13] Invalid Cloud SQL name: Test-3-non-bitnami-boxplot:us-central1:test-3-non-bitnami-sql-instance

I realize that somewhere I wrote the tutorial name by accident instead of my actual instance and database names. So I went back to look at which step I went wrong and I think it was this one:

php wordpress-helper.php setup -n \
    -d ./wordpress-project \
    --db_instance=tutorial-sql-instance \
    --db_name=tutorialdb \
    --db_user=tutorial-user \
    -p [YOUR_PROJECT_ID] \
    --db_password=[YOUR_DATABASE_PASSWORD]

I went back, fixed it, and re-ran it. Then I re-ran gcloud app deploy but it didn't work it still gives the same error.

Any idea how to fix this? It not I am thinking the best thing to do might be to create ANOTHER project and try the tutorial again, this time being more careful with the commands in the terminal.

**Comment by jgacuca567** [comment] 2017-11-24 19:09
When you get an error, post the screenshot, makes it easier to debug. 

Make sure, your credentials are correct. You can start another project from `cd php-docs-samples/appengine/wordpress` just create a new folder when running the **wordpress-helper**

**Comment by bld2104** [comment] 2017-11-24 19:28
Oh sorry I didn't realize that I could post screenshots here, I will do that in the future.

I'm just going to start completely over from the beginning of the tutorial since I'm not totally sure how to implement what you suggested in the last post. It'll be good practice anyway. I'll let you know if I hit another error.

**Comment by jgacuca567** [comment] 2017-11-24 20:01
The error is being caused by your `app.yaml` file, check and make sure your sql instance name is correct.

**Comment by bld2104** [comment] 2017-11-25 04:05
Okay I started completely over, created a brand new project and did everything from scratch. This time it successfully deployed, but when I browsed to the app (https://test-4-boxplot-wordpress.appspot.com/) you can see it says Error establishing database connection. Here's the screenshot of the successful deployment.

<img width="569" alt="screen shot 2017-11-24 at 11 04 30 pm" src="https://user-images.githubusercontent.com/7794512/33227206-e4fed28c-d16b-11e7-8883-da2240197a3b.png">

**Comment by jgacuca567** [comment] 2017-11-25 10:37
I am also receiving the same error. Even though everything is correct. Will try and debug over the weekend to see what's causing the problem

**Comment by bld2104** [comment] 2017-11-25 15:30
I might have found the problem from this article:

https://groups.google.com/forum/#!topic/google-cloud-sql-discuss/Bj9ieB-1by8

I have a second generation instance. I will try to migrate it to a first gen, but if it doesn't let me I will have to start over once more with a separate project. I'll keep you posted.

**Comment by bld2104** [comment] 2017-11-25 15:32
oh wait but the instructions said to create a second gen instance that can't be it... nevermind I will keep searching.

**Comment by bld2104** [comment] 2017-11-25 15:43
I got it working! I changed the user to 'root' and that worked. I am trying my custom theme now. Sorry for so many updates!

**Comment by jgacuca567** [comment] 2017-11-25 15:52
Ok. Test and see if the bootstrap theme will work

**Comment by jgacuca567** [comment] 2017-11-25 15:57
When you changed to root did you leave the password blank or?

**Comment by bld2104** [comment] 2017-11-25 16:24
No I made a password for the root and left that password in. funny you ask though, I actually wasn't sure which one to do, the password I made or blank since some of the help forums said it needs to be blank. So first I tried it with my password, but while I was waiting for it to deployed I changed it to blank in case my password didn't work I'd be ready to try again. 

So then when I added my theme and re-deployed I forgot that I had changed it to blank and after the second deployment it showed the error again. I just changed it back to being the password I created and deployed a third time and now it is working again. 

However I am getting a new error. When I click on "themes" the page looks like this:

<img width="310" alt="screen shot 2017-11-25 at 11 24 14 am" src="https://user-images.githubusercontent.com/7794512/33232367-3f7dc30a-d1d3-11e7-97a9-84d98773fa04.png">

**Comment by bld2104** [comment] 2017-11-25 16:25
Actually that error is happening when i click ANYWHERE in the wp-admin interface.

**Comment by bld2104** [comment] 2017-11-25 16:26
oh wait now it seems to be working - and I activated the boxplot theme and bootstrap is working!! 

THANK YOU SO MUCH!!! I cannot thank you enough for patiently working through this with me! Can I write a review/recommendation for you somewhere as a way of thanking you? LinkedIn or something?

Also, would it be terrible if I asked for help with testing a domain transfer? I see it's already secured which is amazing!

**Comment by bld2104** [comment] 2017-11-25 16:31
By the way, this is the tutorial I followed the first time to transfer a domain name: https://www.onepagezen.com/transfer-domain-google-cloud-platform/

**Comment by jgacuca567** [comment] 2017-11-25 16:35
The domain is the easy part. 

Go to App Engine - Settings - Custom Domains
Then click add a custom domain. Then add the domain.

Not a problem glad to be of assistance. 

Test with the new domain see if it's going to work.

Now you work locally when you are ready to deploy to your domain just run 'gcloud app deploy'.

Let me know how it goes.

**Comment by bld2104** [comment] 2017-11-25 17:19
Thank you! I had to call my host because there is no AAAA option. They told me that I don't need to put all 9 numbers in, just one A and one CNAME. I think they are wrong though because the SSL now isn't working (it's successfully pointing to the Google App when you to go boxplotanalytics.com, but the SSL doesn't work). They told me to give it 3 mins and if the SSL is still not working to call back :(

**Comment by bld2104** [comment] 2017-11-25 17:48
Okay actually it looks like the secure one is pulling from my google app, but the non-secure one no longer redirects to the secure one. Any idea how to fix this?

**Comment by jgacuca567** [comment] 2017-11-25 17:52
Let me get back to you on that. Give it 24 hours see if anything will change

**Comment by bld2104** [comment] 2017-11-26 21:45
Hey James! No change yet, it's still not redirecting. Do you think I should follow the instructions here? https://cloud.google.com/appengine/docs/standard/php/config/mod_rewrite

Or is this the wrong tutorial?

**Comment by jgacuca567** [comment] 2017-11-26 22:11
Check and see if you have a '.htaccess file' in the Wordpress folder. If not create .htaccess file and insert the following

# Force HTTPS
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

Then run gcloud deploy and see if anything will change.

**Comment by bld2104** [comment] 2017-11-26 23:02
I just made my entire .htaccess file this:

# Force HTTPS
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

but unfortunately it doesn't seem to be working.

**Comment by jgacuca567** [comment] 2017-11-26 23:13
Put issue on hold until I find solution.

I don't think the link will work as it shows for standard mode not flexible

**Comment by bld2104** [comment] 2017-12-06 04:56
Hi James - any thoughts on this yet?

**Comment by jgacuca567** [comment] 2017-12-06 20:47
@bld2104 Not yet. 

Cc @bshaffer @tmatsuo 

How do you force SSL on Wordpress GAE?

**Comment by tmatsuo** [comment] 2017-12-06 21:01
@bld2104 

Sorry for the late reply.

@jgacuca567 Thanks for helping


The Flex runtime uses nginx, so unfortunately .htaccess doesn't work.

If you use the wordpress helper script, you should have a file `nginx-app.conf` as follows:

```
location / {
    try_files $uri /index.php?q=$uri&$args;
}

location ~ ^/wp-admin {
    try_files $uri $uri/index.php?$args;
}
```

Edit this file and make it like the following:
```
set $test "";

if ($http_x_forwarded_proto = 'http') {
    set $test "http";
}

if ($request_uri != '/wp-cron.php') {
   set $test "${test}-non-cron";
}

if ($test = 'http-non-cron') {
    return 301 https://$host$request_uri;
}

location / {
    try_files $uri /index.php?q=$uri&$args;
}

location ~ ^/wp-admin {
    try_files $uri $uri/index.php?$args;
}
```

Then it will auto redirect to the https site.

**Comment by tmatsuo** [comment] 2017-12-06 21:03
If you are using the standard env, it's a different story though.

@bld2104 Can you show me the current `app.yaml` file?

**Comment by bld2104** [comment] 2017-12-06 21:29
@tmatsuo sure thing thank you for the help! Here are the contents of my current app.yaml file:

`runtime: php
env: flex

beta_settings:
  cloud_sql_instances: test-4-boxplot-wordpress:us-central1:test-4-boxplot-wordpress

runtime_config:
  document_root: wordpress

env_variables:
  WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname`

**Comment by tmatsuo** [comment] 2017-12-06 21:30
@bld2104 Alright, then follow the instructions on https://github.com/GoogleCloudPlatform/php-docs-samples/issues/489#issuecomment-349773430

and let me know how it goes

**Comment by jgacuca567** [comment] 2017-12-07 01:01
@tmatsuo Works like a charm. 
@bld2104 did you change your **nginx-app.conf** file?

**Comment by bld2104** [comment] 2017-12-07 02:17
@jgacuca567 and @tmatsuo yes sorry for the delay, I did update it and yes it looks like it is working! I think some pages might have gotten deleted in the process? I have to run an errand but will check it when I get back in an hour or so.

**Comment by bld2104** [comment] 2017-12-07 02:52
@jgacuca567 and @tmatsuo  Oh never mind, that was something unrelated. So everything is working now! Thank you both SO SO much! 

James - Thank you for sticking with me patiently through this whole thing! I can't tell you how much I appreciate it!

**Comment by tmatsuo** [comment] 2017-12-07 04:25
Okay, closing the issue

**Closed by tmatsuo** 2017-12-07 04:25 UTC
