### ISSUE TITLE
Undefined method Google\Cloud\AutoMl\V1\TextExtractionDatasetMetadata::setSourceLanguageCode()

### ISSUE THREAD

**Issue by jmpardos** [GoogleCloudPlatform/php-docs-samples#1228] opened 2020-11-27 09:34 UTC
Hi.

As the title says there is an error on TextExtractionDatasetMetadata class because setSourceLanguageCode method doesn't exists.

I'm creating a dataset with AutoML PHP Api right now, as in the example: https://cloud.google.com/translate/automl/docs/datasets

But when it executes the next lines, the process break up showing the message in the title.

$metadata = (new TextExtractionDatasetMetadata())
        ->setSourceLanguageCode($sourceLanguage)
        ->setTargetLanguageCode($targetLanguage);

I've checked out the class and there's no method named like that, indeed.

Also I tried to use other alternative similar classes like TranslationModelMetadata, but in this case the API returns that expect TextExtractionDatasetMetadata class object.

Could you check it?

Thanks in advance.

Greetings.

**Comment by bshaffer** [comment] 2020-12-07 18:50
Hi there! Thank you for reporting this! 

I believe the issue is that the sample is wrong. The class used should be `TranslationDatasetMetadata` and not `TextExtractionDatasetMetadata`:

```php
use Google\Cloud\AutoMl\V1\AutoMlClient;
use Google\Cloud\AutoMl\V1\Dataset;
use Google\Cloud\AutoMl\V1\TranslationDatasetMetadata;

/** Uncomment and populate these variables in your code */
// $projectId = '[Google Cloud Project ID]';
// $location = 'us-central1';
// $displayName = 'your_dataset_name';
// $sourceLanguage = 'en';
// $targetLanguage = 'ja';

$client = new AutoMlClient();

try {
    // resource that represents Google Cloud Platform location
    $formattedParent = $client->locationName(
        $projectId,
        $location
    );

    $metadata = (new TranslationDatasetMetadata())
        ->setSourceLanguageCode($sourceLanguage)
        ->setTargetLanguageCode($targetLanguage);
    $dataset = (new Dataset())
        ->setDisplayName($displayName)
        ->setTranslationDatasetMetadata($metadata);

    // create dataset with the above location and metadata
    $operationResponse = $client->createDataset($formattedParent, $dataset);
    $operationResponse->pollUntilComplete();
    if ($operationResponse->operationSucceeded()) {
        $result = $operationResponse->getResult();

        // display dataset information
        $splitName = explode('/', $result->getName());
        printf('Dataset name: %s' . PHP_EOL, $result->getName());
        printf('Dataset id: %s' . PHP_EOL, end($splitName));
    } else {
        $error = $operationResponse->getError();
        // handleError($error)
    }
} finally {
    $client->close();
}
```

**Comment by bshaffer** [comment] 2020-12-07 18:52
Fixed in https://github.com/GoogleCloudPlatform/php-docs-samples/commit/419b460b97f41603fb3e250e2531210b70e2ea57

**Comment by bshaffer** [comment] 2020-12-07 19:15
Closing as the docs is now updated and fixed. However, we **really** need to merge #990 so these issues don't happen again.

Thank you @jmpardos for reporting this

**Closed by bshaffer** 2020-12-07 19:15 UTC
Labels: :rotating_light:, api: automl, samples, triage me, type: bug
