### ISSUE TITLE
WP-cli, "No project ID provided"

### ISSUE THREAD

**Issue by bjornjo** [GoogleCloudPlatform/php-docs-samples#366] opened 2017-05-15 21:16 UTC
I want to install a plugin for my wordpress project with flexible environment.
The readme.md tells me to do this:

***
You can also use the wp-cli utility in the project’s vendor directory as follows (you have to run Cloud SQL Proxy or local mysql server for this tool to work):

To update all the plugins
$ vendor/bin/wp plugin update --all --path=wordpress
To update all the themes
$ vendor/bin/wp theme update --all --path=wordpress
***

However, after starting the cloud sql proxy and running the command, I get this error:
PHP Fatal error:  Uncaught Google\Cloud\Core\Exception\GoogleException: No project ID was provided, and we were unable to detect a default project ID.

What am I doing wrong?

**Comment by tmatsuo** [comment] 2017-05-15 22:41
I can not reproduce the issue.

Potentially, it can be fixed by creating a service account, downloading the json key, and setting an envvar `GOOGLE_APPLICATION_CREDENTIALS` envvar to that file.

**Comment by bshaffer** [comment] 2017-05-16 20:43
Yes, this is because it is expecting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to be set, or the variable IS set and the path is invalid or the credentials it points to do not contain a project ID.

We can optionally add a `--project` option to the script, or highlight in the README that this env var needs to be set.

**Comment by sneakersgames** [comment] 2017-06-09 13:28
A --project would be much cleaner since you can have multiple Google Cloud projects and you don't want to change your envvar each time.

**Comment by urmamb** [comment] 2017-09-09 20:22
I am also having thee same issue can any one explain it wth practical example code instead of a theory?

**Comment by NiltonFelicio** [comment] 2017-09-22 11:51
I'm facing the same problems. In what document do I put this GOOGLE_APPLICATION_CREDENTIALS? Could include this in the README.

**Comment by jgacuca567** [comment] 2017-09-22 16:42
@NiltonFelicio have you created a service account? 
@urmamb  have you created a service account? 

Check out this link on how to Create A Service Account - https://cloud.google.com/iam/docs/creating-managing-service-accounts

**Comment by NiltonFelicio** [comment] 2017-09-22 17:00
Thanks @jgacuca567  for helping.
Yes I created the service account and downloaded the .json file.
Even the whole README was done. I am having this problem to start location. After the deployer I can not update plugins, themes and the own Wordpress.

I tried to include GOOGLE_APPLICATION_CREDENTIALS in wp-config.php, but I was not very successful, I still get the same error.

like this in wp-config:
putenv('GOOGLE_APPLICATION_CREDENTIALS=/secure-place/my-service-account.json');

*Is it that in the service account I have to include permissions would it be pro cloud storage or for SQL instance?

**Comment by NiltonFelicio** [comment] 2017-09-23 04:08
I solved the problem this way:
[here](https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/44)

replace these lines in wp-config.php:

// Register GCS stream wrapper
require_once(__DIR__ . '/../vendor/autoload.php');
$storageClient = new Google\Cloud\Storage\StorageClient();
$storageClient->registerStreamWrapper();

for these:

// Register GCS stream wrapper
require_once(__DIR__ . '/../vendor/autoload.php');
$config = ['projectId' => 'my-ID-project'];
$storageClient = new Google\Cloud\Storage\StorageClient($config);
$storageClient->registerStreamWrapper();

I do not know if it would be the best solution, but it does.
GoogleException: No project ID was provided, and we were unable to detect a default project ID.

Now another problem has appeared
The requested URL /wp-admin/install.php was not found on this server.

Looking at folders /wp-admin/install.php are at that address.
Has anyone ever faced this problem? Have I skipped any important points in the README instructions?

**Comment by NiltonFelicio** [comment] 2017-09-24 04:21
If someone is experiencing the same problem described above.
Correct as follows: first start this command `$ vendor/bin/wp server --path=wordpress`

**Comment by khera** [comment] 2017-10-04 12:52
I get the same error when running `dev_appserver.py .` and visiting the dev web page.

**Comment by jgacuca567** [comment] 2017-10-18 01:32
@khera were you able to get the fix, are you still receiving the error?

**Comment by khera** [comment] 2017-10-18 01:46
@jgacuca567 i just set the GCLOUD_PROJECT environment variable and the wp command worked. So I continue to do that. I reviewed the code and that is a correct fix.

**Comment by jgacuca567** [comment] 2017-10-18 12:56
@tmatsuo, @bshaffer  Please close the issue

**Closed** 2017-10-19 11:46 UTC
