### ISSUE TITLE
Dialogflow - how to get JSON type fulfilmentText for testing detect intent?

### ISSUE THREAD

**Issue by carrotis** [GoogleCloudPlatform/php-docs-samples#959] opened 2019-09-17 06:05 UTC
Hi all

My Dialogflow server return JSON type strings instead of text.

eg.
{
 "custom": {
      "text" : "hi",
      "img_url": "a.com/a.gif",
   }
}

I test using below command, but there are no return values.
>  php .\dialogflow.php detect-intent-texts -vvvvv PROJECT_ID  HI
>  PHP Warning:  Class '\PHPUnit_Framework_ExpectationFailedException' not found in C:\Users\r2sky\DEV\php-docs-samples\dialogflow\vendor\google\cloud-tools\src\TestUtils\ExponentialBackoffTrait.php on line 23
>  Session path: projects/PROJECTID/agent/sessions/5d807513a4f9d
>  ====================
>  Query text: butterfly
>  Detected intent: 0001HI (confidence: 1.000000)
>  Fulfilment 

> text:

So, I was looking for solve the problem, I found there are two functions.
In detect_intent_texts.php

// origin
     $fulfilmentText = $queryResult->getFulfillmentText();
// add for testing
     $fulfilmentJson = $queryResult->getFulfillmentMessages();

But both are not work.
How to I print JSON type messages using Dialogflow PHP client ?

Thanks.

**Comment by bshaffer** [comment] 2019-10-07 17:37
It's very strange you are receiving a message about `phpunit` outside of running the tests. That shouldn't happen. However since that's a warning, I don't think that has to do with the issue. 

My guess is the texts you're sending in are not returning results. The texts we use in our tests are `'hello'`, `'book a meeting room'`, and `'mountain view'`. Try these and see if you get any results.

**Comment by bshaffer** [comment] 2019-10-07 17:50
Closing as duplicate of #942

**Closed by bshaffer** 2019-10-07 17:50 UTC
Labels: type: question

**Comment by bshaffer** [comment] 2019-10-17 18:19
This is now fixed, please give this another try!
